I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/Day 1/9 economics.rpy", line 16, in script call
    call econ1kahoot1
  File "game/story/Day 1/9 economics.rpy", line 20, in script call
    call kahootGame(question=kahoot["econ1"], time_range=10)
  File "game/minigames/kahoot/kahootscreen.rpy", line 14, in script
    label kahootGame(kahoot, show_result=True, **options):
Exception: Required parameter kahoot has no value.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/Day 1/9 economics.rpy", line 16, in script call
    call econ1kahoot1
  File "game/story/Day 1/9 economics.rpy", line 20, in script call
    call kahootGame(question=kahoot["econ1"], time_range=10)
  File "game/minigames/kahoot/kahootscreen.rpy", line 14, in script
    label kahootGame(kahoot, show_result=True, **options):
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 772, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 151, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 119, in apply
    raise Exception("Required parameter %s has no value." % name)
Exception: Required parameter kahoot has no value.

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
sze-the game 0.0
