I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/screens/developer.rpy", line 4, in prepare_screen
    screen developerScreen:
  File "game/screens/developer.rpy", line 4, in prepare
    screen developerScreen:
Exception: A screen named label_description does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/fiendchain/Downloads/sze-the-game/renpy/bootstrap.py", line 305, in bootstrap
    renpy.main.main()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/main.py", line 499, in main
    run(restart)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/main.py", line 88, in run
    renpy.display.screen.prepare_screens()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/screen.py", line 859, in prepare_screens
    s.ast.prepare_screen()
  File "game/screens/developer.rpy", line 4, in prepare_screen
    screen developerScreen:
  File "game/screens/developer.rpy", line 4, in prepare
    screen developerScreen:
  File "/home/fiendchain/Downloads/sze-the-game/renpy/sl2/slast.py", line 1583, in prepare
    raise Exception("A screen named {} does not exist.".format(self.target))
Exception: A screen named label_description does not exist.

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
sze-the game 0.0
