I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/minigames/kahoot/kahootscreen.rpy", line 31, in script
    call screen kahootscreen(question=question["question"], answers=question["answers"], **options)
  File "renpy/common/000statements.rpy", line 480, in execute_call_screen
    args, kwargs = a.evaluate()
  File "game/minigames/kahoot/kahootscreen.rpy", line 31, in <module>
    call screen kahootscreen(question=question["question"], answers=question["answers"], **options)
NameError: name 'question' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/minigames/kahoot/kahootscreen.rpy", line 31, in script
    call screen kahootscreen(question=question["question"], answers=question["answers"], **options)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 1774, in execute
    self.call("execute")
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 1762, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/statements.py", line 163, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 480, in execute_call_screen
    args, kwargs = a.evaluate()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 181, in evaluate
    kwargs[k] = renpy.python.py_eval(v, locals=scope)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/python.py", line 1794, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/python.py", line 1788, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/minigames/kahoot/kahootscreen.rpy", line 31, in <module>
    call screen kahootscreen(question=question["question"], answers=question["answers"], **options)
NameError: name 'question' is not defined

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
sze-the game 0.0
