I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/script.rpy", line 33, in script call
    sze "Or perhaps it conjures an image of quaint Parisian cafes at night"
  File "game/minigames/pong/pongscreen.rpy", line 9, in script
    $ _previousMusic = musicHistory[-1]
  File "game/minigames/pong/pongscreen.rpy", line 9, in <module>
    $ _previousMusic = musicHistory[-1]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/script.rpy", line 33, in script call
    sze "Or perhaps it conjures an image of quaint Parisian cafes at night"
  File "game/minigames/pong/pongscreen.rpy", line 9, in script
    $ _previousMusic = musicHistory[-1]
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 826, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/minigames/pong/pongscreen.rpy", line 9, in <module>
    $ _previousMusic = musicHistory[-1]
IndexError: list index out of range

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
sze-the game 0.0
