I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/script.rpy", line 6, in script
    show screen diary_button
  File "renpy/common/000statements.rpy", line 467, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen diary_button is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/script.rpy", line 6, in script
    show screen diary_button
  File "C:\Users\DerX\Documents\GitHub\sze-the-game\renpy\ast.py", line 1774, in execute
    self.call("execute")
  File "C:\Users\DerX\Documents\GitHub\sze-the-game\renpy\ast.py", line 1762, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\DerX\Documents\GitHub\sze-the-game\renpy\statements.py", line 163, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 467, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "C:\Users\DerX\Documents\GitHub\sze-the-game\renpy\display\screen.py", line 1022, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen diary_button is not known.


Windows-8-6.2.9200
Ren'Py 6.99.13.2919
sze-the game 0.0
